---
micronaut:
    application:
        name: micronaut-kotlin-jwt

---
micronaut:
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: "${JWT_GENERATOR_SIGNATURE_SECRET:ac6dc416-0ea7-42e3-9d39-d3dddcc01027}"
        bearer:
          prefix: Token
    intercept-url-map:
      - pattern: /*
        access:
          - isAuthenticated()
      -
        pattern: /users
        http-method: POST
        access:
          - isAnonymous()
      -
        pattern: /users/login
        http-method: POST
        access:
          - isAnonymous()
---
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5434/realworld`}
    username: ${JDBC_USER:realworld}
    password: ${JDBC_PASSWORD:realworld}
    driverClassName: org.postgresql.Driver
